# Generated by Django 4.2.5 on 2023-09-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_brth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(default='', max_length=50)),
                ('Date_of_death', models.DateField(blank=True, null=True)),
                ('Place_of_death', models.CharField(default='', max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='auther/')),
                ('bio', models.TextField(default='')),
            ],
            options={
                'db_table': 'auther',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pages', models.IntegerField()),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('bio', models.TextField()),
                ('auther', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_authors.authermodel')),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_authors.genremodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AddField(
            model_name='authermodel',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_authors.genremodel'),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
