# Generated by Django 4.2.5 on 2023-09-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_authors', '0004_remove_genremodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authermodel',
            old_name='Date_of_death',
            new_name='date_of_death',
        ),
        migrations.RenameField(
            model_name='authermodel',
            old_name='Place_of_death',
            new_name='place_of_death',
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
